*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZAFPMVW_001.....................................*
FORM GET_DATA_ZAFPMVW_001.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZAFPMT_004 WHERE
(VIM_WHERETAB) .
    CLEAR ZAFPMVW_001 .
ZAFPMVW_001-MANDT =
ZAFPMT_004-MANDT .
ZAFPMVW_001-ID =
ZAFPMT_004-ID .
ZAFPMVW_001-DESCRICAO =
ZAFPMT_004-DESCRICAO .
<VIM_TOTAL_STRUC> = ZAFPMVW_001.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZAFPMVW_001 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZAFPMVW_001.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZAFPMVW_001-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZAFPMT_004 WHERE
  ID = ZAFPMVW_001-ID .
    IF SY-SUBRC = 0.
    DELETE ZAFPMT_004 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZAFPMT_004 WHERE
  ID = ZAFPMVW_001-ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZAFPMT_004.
    ENDIF.
ZAFPMT_004-MANDT =
ZAFPMVW_001-MANDT .
ZAFPMT_004-ID =
ZAFPMVW_001-ID .
ZAFPMT_004-DESCRICAO =
ZAFPMVW_001-DESCRICAO .
    IF SY-SUBRC = 0.
    UPDATE ZAFPMT_004 ##WARN_OK.
    ELSE.
    INSERT ZAFPMT_004 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZAFPMVW_001-UPD_FLAG,
STATUS_ZAFPMVW_001-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZAFPMVW_001.
  SELECT SINGLE * FROM ZAFPMT_004 WHERE
ID = ZAFPMVW_001-ID .
ZAFPMVW_001-MANDT =
ZAFPMT_004-MANDT .
ZAFPMVW_001-ID =
ZAFPMT_004-ID .
ZAFPMVW_001-DESCRICAO =
ZAFPMT_004-DESCRICAO .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZAFPMVW_001 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZAFPMVW_001-ID TO
ZAFPMT_004-ID .
MOVE ZAFPMVW_001-MANDT TO
ZAFPMT_004-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZAFPMT_004'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZAFPMT_004 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZAFPMT_004'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
